name = "ledger-signer"
description = "Ledger Signer"
repository = "MystenLabs/rust-signers"
main_branch = "main"
installation_type = "standalone"
network_based = false
nightly_toolchain = "nightly"
shared_repo_binary = true
