name = "move-analyzer"
description = "Move Analyzer"
repository = "MystenLabs/sui"
main_branch = "main"
installation_type = "archive"
network_based = true
supported_networks = ["testnet", "devnet", "mainnet"]
default_network = "testnet"
shared_repo_binary = true
