name = "site-builder"
description = "Walrus Sites Builder"
repository = "MystenLabs/walrus-sites"
main_branch = "main"
installation_type = "archive"
network_based = true
supported_networks = ["mainnet"]
default_network = "mainnet"
supports_debug = false
cargo_package = ""
nightly_toolchain = ""
shared_repo_binary = false
