name = "sui"
description = "Sui CLI"
repository = "MystenLabs/sui"
main_branch = "main"
installation_type = "archive"
network_based = true
supported_networks = ["testnet", "devnet", "mainnet"]
default_network = "testnet"
supports_debug = true
